### ISSUE TITLE
Xcode: .m files aren't added from an addon's library src folder

### ISSUE THREAD

**Issue by bangnoise** [ofZach/projectGeneratorSimple#57]
[ofxSyphon](https://github.com/astellato/ofxSyphon) has a .m file in libs/Syphon/src. The project generator correctly adds the accompanying .h file to the project, but fails to add the .m (Objective C source) to the generated Xcode project.

**Comment by danomatika** [comment]
This is fixed in: https://github.com/ofZach/projectGeneratorSimple/pull/62

**Comment by bangnoise** [comment]
Yep fixed thanks @danomatika
