### ISSUE TITLE
Anoying bug with PG and Codeblocks

### ISSUE THREAD

**Issue by gorkacortazar** [ofZach/projectGeneratorSimple#61]
Zach:

I have been having an anoying bug using the PG version that comes with ofx 0.8.4. When you create a new project, codeblocks takes ages to open unless you close the PG app. To replicate:
- Start the project generator (with codeblocks closed)
- Create a new project with a few addons
- Open the resulting workspace (double click) without closing the PG

In my macbookpro with windows8 (via bootcamp) it can take up to 5 minutes to open. At the beginning I was thinking that the problem was mi CB, but after that I discovered that closing the PG solved the issue.

Until there is a better way to update projects in the PG, is a bug that can be specially annoying when updating projects that have many addons (is very easy to forget to add one until you check the result).

Can it be related to some file created but not properly closed at os level until you close the PG?

**Comment by ofZach** [comment]
thanks for the report, some questions -- is it only on projects that it's just made or on any project that it's made while it's open?  If you close the PG and re-open it, do you see the same thing?

**Comment by gorkacortazar** [comment]
Haven't tried, but i will it a try tomorrow, I'll keep you posted.
